[package]
name = "SandSim"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Bevy Core
bevy = { version = "0.18", features = ["multi_threaded", "bevy_winit", "bevy_render", "bevy_asset", "bevy_core_pipeline"] }

# UI
bevy_egui = "0.39"

# GPU Data Handling
bytemuck = { version = "1.19", features = ["derive"] }
encase = { version = "0.10", features = ["glam"] } # Handles GPU padding/alignment

# Utilities
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26"
bitflags = "2.11"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
